sudo: required
language: node_js
dist: xenial
node_js:
  - 10.22.0
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - export SENTRY_RELEASE=$TRAVIS_COMMIT
install:
  - yes n | npm install
  - envsubst < src/environments/constants.template.ts > src/environments/constants.ts
  - echo "$TRAVIS_BRANCH"
  - |
    if [ "$TRAVIS_BRANCH" = "master" ]; then
      cp src/environments/environment.prod.ts src/environments/environment.ts
      echo "Prod Env Enabled"
      npm run build-prod
    fi
  - |
    if [ "$TRAVIS_BRANCH" != "master" ]; then
      cp src/environments/environment.dev.ts src/environments/environment.ts
      echo "Prod Env Disabled"
      npm run build
    fi
script:
  - npm run test
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -e "ssh -o StrictHostKeyChecking=no" -r dist/* $SB_WEB_HOST:~/switchboard-dapp/develop
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: rsync -e "ssh -o StrictHostKeyChecking=no" -r dist/* $SB_WEB_HOST:~/switchboard-dapp/master
    on:
      branch: master
after_deploy:
  - curl -sL https://sentry.io/get-cli/ | bash
  - chmod +x ./sentry-upload.sh
  - ./sentry-upload.sh
