name: Create Jira Ticket from GitHub Issue

on:
  issues:
    types: ['opened']

jobs:
  create-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    outputs:
      issueId: ${{ steps.save-id.outputs.issueId }}
    steps: 
      - name: Login to JIRA
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create JIRA Ticket
        id: create
        uses: atlassian/gajira-create@v2.0.1
        with:
          project: Switchboard
          issuetype: Bug
          summary: "${{ github.event.issue.title }}"

      - name: Save Issue ID
        id: save-id
        run: |
          ID='${{ steps.create.outputs.issue }}'
          echo ::set-output name=issueId::${ID}
  
  find-labels:
    runs-on: ubuntu-latest
    needs:
      - create-issue
    outputs:
      labels: ${{ steps.generate-labels.outputs.labels }}
    steps:
      - name: Generate Labels
        id: generate-labels
        run: |
          LABELS='${{ toJSON(github.event.issue.labels.*.name) }}'
          echo ::set-output name=labels::${LABELS}      
  
  add-labels:
    runs-on: ubuntu-latest
    needs:
      - create-issue
      - find-labels
    strategy:
      matrix:
        label: ${{ fromJSON(needs.find-labels.outputs.labels) }}
    steps:
      - name: Setup Jira
        uses: atlassian/gajira-cli@v2.0.2
        
      - name: Login to JIRA
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Add label
        run: jira labels add ${{ needs.create-issue.outputs.issueId }} "${{ matrix.label }}"
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}