name: Create Jira Ticket from GitHub Issue

on:
  issues:
    types: ['opened']

jobs:
  create-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    outputs:
      issueId: ${{ steps.save-issue-id.outputs.issueId }}
    steps:
      - name: Login to JIRA
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create JIRA Ticket
        id: create
        uses: atlassian/gajira-create@v2.0.1
        with:
          project: SWTCH
          issuetype: Bug
          summary: '${{ github.event.issue.title }} (GitHub Issue ${{ github.event.issue.number }})'
          description: '${{ github.event.issue.body }} See issue: ${{ github.event.issue.html_url }}'

      - name: Save Issue ID
        id: save-issue-id
        run: |
          ID='${{ steps.create.outputs.issue }}'
          echo ::set-output name=issueId::${ID}

  add-switchboard-label:
    runs-on: ubuntu-latest
    needs: save-issue-id
    steps:
      - name: Setup Jira CLI
        uses: atlassian/gajira-cli@v2.0.2

      - name: Login to Jira
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Add label
        run: jira labels add ${{ needs.save-issue-id.outputs.issueId }} 'Switchboard'
