name: Deploy

on:
  push:
    branches: ['develop', 'master']
  pull_request:
    branches: ['develop', 'master']

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  deploy:
    runs-on: ubuntu-latest
    needs: cancel-previous
    env:
      SB_APP_DIR: /home/travis/switchboard-dapp
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10.22.0'
          registry-url: https://registry.npmjs.org/

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Install npm packages
        run: |
          npm install
          envsubst < src/environments/constants.template.ts > src/environments/constants.ts

      - name: Run Test
        run: |
          npm run test:headless

      - name: Prepare for non-master branch
        if: github.ref != 'refs/heads/master'
        run: |
          cp src/environments/environment.dev.ts src/environments/environment.ts
          echo "Prod Env Disabled"
          npm run build-stedin
          npm run setup-sentry
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: Deploy stedin
        if: github.ref == 'refs/heads/develop'
        uses: burnett01/rsync-deployments@5.0
        with:
          switches: -r
          path: dist/*
          remote_path: ${{ env.SB_APP_DIR }}/stedin-dev
          remote_host: ${{ secrets.SB_WEB_HOST }}
          remote_user: ${{ secrets.GH_SWITCHBOARD_USERNAME }}
          remote_key: ${{ secrets.GH_SWITCHBOARD_SSH_KEY }}

      - name: Sentry Release Staging
        uses: getsentry/action-release@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        if: github.ref == 'refs/heads/develop'
        with:
          environment: ${{ secrets.SENTRY_STAGING_ENV }}
          ignore_missing: true
